# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fibonacci <- function(n) {
    .Call(`_surveyfreq_fibonacci`, n)
}

sort_cpp <- function(arr, method = "merge", overwrite = TRUE) {
    .Call(`_surveyfreq_sort_cpp`, arr, method, overwrite)
}

#' Generate the weighted frequency table
#'
#' Generate the weighted frequency table with jackknife or BRR similar with PROC SURVEYFREQ procedure.
#' It takes roughly 10+ seconds to process 10
#' @param arr A \code{vector} (integer, double, character, logical or complex) of dimension M
#' @param based_wt A \code{vector} of dimension of M
#' @param rep_wts A \code{matrix} of M x N
#' @param includeNA Logical. Should missing values (including NaN) be removed?
#' @param NA_wt double Assign a constance value if weight is missing
#' @param varmethod Character, "jackknife" or "BRR"
#' @param BRRfay 0 - 1, only available when varmethod=="BRR"
#' @author Wenke Huang
#' @export
#' @examples
#' \dontrun{
#' # Generate a vector, based weight and replicated weights
#' arr=sample(1:10, 1000, replace=TRUE)
#' based_wt=runif(1000)
#' rep_wts=matrix(runif(1000*80), ncol=80)
#'
#' # Generate table
#' surveyfreq2(arr, based_wt, rep_wts)
#' }
surveyfreq <- function(arr, based_wt = NULL, rep_wts = NULL, includeNA = FALSE, NA_wt = 1, varmethod = "jackknife", BRRfay = 0) {
    .Call(`_surveyfreq_surveyfreq`, arr, based_wt, rep_wts, includeNA, NA_wt, varmethod, BRRfay)
}

SGD_lm <- function(X, y, intercept = TRUE, iter = 1000L, learning_rate = 0.001) {
    .Call(`_surveyfreq_SGD_lm`, X, y, intercept, iter, learning_rate)
}

